language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - nightly
notifications:
  email:
      - ward9250@gmail.com
after_success:
#  - julia -e 'using Pkg; Pkg.add("Coverage")'
#  - julia -e 'using Coverage; import FASTX; cd(dirname(dirname(pathof(FASTX)))); Codecov.submit(process_folder())'
#  - julia -e 'import FASTA; cd(dirname(dirname(pathof(FASTA)))); include(joinpath("docs", "make.jl"))'
   - julia --project=coverage/ -e 'using Pkg; Pkg.instantiate()'
   - julia --project=coverage/ coverage/coverage.jl
  
jobs:
    include:
        - stage: "Documentation"
          julia: 1.0
          os: linux
          script:
            - julia --project=docs/ -e 'using Pkg; Pkg.instantiate();
                                        Pkg.develop(PackageSpec(path=pwd()))'
            - julia --project=docs/ docs/make.jl
          after_success: skip